build.sbt

* Update scoverage configuration.
* Change default port to same as service manager.

SBT update.

---

app/connectors/ChildBenefitEntitlementConnector.scala
app/connectors/HttpReadsWrapper.scala
app/controllers/NoAccountFoundController.scala
app/controllers/auth/AuthController.scala
app/controllers/auth/ChildBenefitAuth.scala
app/utils/handlers/ErrorHandler.scala

[SB-1051](https://jira.tools.tax.service.gov.uk/browse/SB-1051)
Expand logging to both:
- better track errors
- debug messages for developmental tracking of behaviour

SB-1051: Additional Logging

---

app/config/AllowlistFilter.scala
conf/application.conf

This ensures the user is redirected to a page not just a blank screen

SB-1095 - Update allow list filter

---

app/controllers/CheckYourAnswersController.scala
app/controllers/DummyFlagController.scala
app/controllers/NationalityQuestionController.scala
app/controllers/actions/FeatureFlagAction.scala
app/controllers/actions/FeatureFlagActionFactory.scala
conf/application.conf
conf/messages.en
test/controllers/CheckYourAnswersControllerSpec.scala

[SB-1129](https://jira.tools.tax.service.gov.uk/browse/SB-1129)
Add feature flag and associated actions for future features currently on the road map

SB-1129: Feature Flags for Child Benefits Roadmap

---

app/views/CheckYourAnswersView.scala.html
app/views/DummyFlagView.scala.html
app/views/ErrorTemplate.scala.html
app/views/IndexView.scala.html
app/views/JourneyRecoveryContinueView.scala.html
app/views/JourneyRecoveryStartAgainView.scala.html
app/views/NoAccountFoundView.scala.html
app/views/NotFoundView.scala.html
app/views/ProofOfEntitlement.scala.html
app/views/UnauthorisedView.scala.html
app/views/cob/CannotVerifyAccountView.scala.html
app/views/components/BulletList.scala.html
app/views/components/CaptionHeader.scala.html
app/views/components/HelplineSection.scala.html
app/views/components/PrintLink.scala.html
app/views/paymenthistory/NoPaymentHistory.scala.html
app/views/paymenthistory/PaymentHistory.scala.html
app/views/templates/ServiceUnavailableTemplate.scala.html
conf/messages.cy
conf/messages.en

Refactored the majority of views to use twirl components, messages files should now be free of html and views more readable.

Component refactor

---

app/views/ProofOfEntitlement.scala.html
app/views/paymenthistory/NoPaymentHistory.scala.html
app/views/paymenthistory/PaymentHistory.scala.html

internal service links now open in same tab

SB-1213: new tab regression bug

---

app/controllers/ProofOfEntitlementController.scala
app/services/PaymentHistoryService.scala
app/utils/helpers/ChildBenefitEntitlementHelper.scala
app/utils/helpers/StringHelper.scala
test-utils/generators/ModelGenerators.scala
test/services/AuditServiceSpec.scala
test/utils/TestData.scala
test/utils/helpers/ChildBenefitEntitlementHelperSpec.scala
test/utils/helpers/StringHelperSpec.scala

[SB-1210](https://jira.tools.tax.service.gov.uk/browse/SB-1210)
- utils to format ChildBenefitEntitlement for front end presentation
- associated Unit Test Suites

SB-1210: Format user name and address for the front end

---

test/utils/helpers/ChildBenefitEntitlementHelperSpec.scala

[SB-1210](https://jira.tools.tax.service.gov.uk/browse/SB-1210)
The data from the ticket being explicitly tested in cases.

SB-1210: Add examples from original ticket as explicit Unit Tests

---

app/services/ChangeOfBankService.scala
app/utils/helpers/ChildBenefitEntitlementHelper.scala
app/utils/helpers/ClaimantBankInformationHelper.scala
test-utils/generators/ModelGenerators.scala
test/utils/helpers/ChildBenefitEntitlementHelperSpec.scala
test/utils/helpers/ClaimantBankInformationHelperSpec.scala
test/utils/helpers/StringHelperSpec.scala
test/views/cob/ChangeAccountViewSpec.scala

[SB-1210](https://jira.tools.tax.service.gov.uk/browse/SB-1210)
Extend front end formatting to Entitlement Children's names and Claimant Bank Info

SB-1210: More front end info formatting

---

app/views/ftnae/SchoolOrCollegeView.scala.html
conf/messages.cy
conf/messages.en
test/controllers/ftnae/SchoolOrCollegeControllerSpec.scala

SB-1195 & SB-1333 - Create and translate ftnae page - Confirm school or college

---

app/views/ftnae/HowManyYearsView.scala.html
app/views/ftnae/LiveWithYouInUKView.scala.html
app/views/ftnae/SchoolOrCollegeView.scala.html
app/views/ftnae/TwelveHoursAWeekView.scala.html
app/views/ftnae/WhichYoungPersonView.scala.html
app/views/ftnae/WhyYoungPersonNotListedView.scala.html
app/views/ftnae/WillCourseBeEmployerProvidedView.scala.html
app/views/ftnae/WillYoungPersonBeStayingView.scala.html
conf/messages.en

SB-1203 - Create Page - Young Person not listed for FTNAE

---

app/views/ftnae/CannotFindYoungPersonView.scala.html
conf/messages.en

SB-1315 - Create Page - Cannot find Young Person

---

app/views/ftnae/ExtendPaymentsView.scala.html
conf/messages.en

SB-1240 - Create start page content without API calls

---

app/controllers/ftnae/CheckYourAnswersController.scala
app/controllers/ftnae/WhichYoungPersonController.scala
app/forms/ftnae/WhichYoungPersonFormProvider.scala
app/pages/ftnae/WhichYoungPersonPage.scala
app/utils/navigation/Navigator.scala
app/viewmodels/checkAnswers/WhichYoungPersonSummary.scala
app/views/components/Warning.scala.html
app/views/ftnae/CheckYourAnswersView.scala.html
conf/messages.en
test/controllers/ftnae/CheckYourAnswersControllerSpec.scala
test/controllers/ftnae/WhichYoungPersonControllerSpec.scala
test/forms/WhichYoungPersonFormProviderSpec.scala
test/utils/navigation/NavigatorSpec.scala

SB-1206 - Update Check your answers page with correct content

---

app/controllers/ftnae/PaymentsExtendedController.scala
app/models/ftnae/CourseDuration.scala
app/services/FtnaeService.scala
app/views/ftnae/PaymentsExtendedView.scala.html
conf/messages.en
test/controllers/ftnae/PaymentsExtendedControllerSpec.scala
test/services/FtnaeServiceSpec.scala

SB-1207 - Content changes for ftnae confirmation submission page

---

conf/messages.cy

[SB-1343](https://jira.tools.tax.service.gov.uk/browse/SB-1343)
Change to the Welsh on the Why Young Person Not Listed page requested by the WLU.

Change to Welsh requested by the WLU

---

app/views/ftnae/CheckYourAnswersView.scala.html
app/views/ftnae/PaymentsExtendedView.scala.html
conf/messages.cy
conf/messages.en

[[SB-1654]](https://jira.tools.tax.service.gov.uk/browse/SB-1654)
Move Change of Circumstances text from the Change Your Answers page to the Payments Extended page

[SB-1654] Move Change of Circumstances text

---

conf/messages.cy
conf/messages.en

[[SB-1338]](https://jira.tools.tax.service.gov.uk/browse/SB-1338)
Some corrections to Welsh and provide a Welsh translation for site.change.

Further Welsh updates to match expected

---

app/views/ProofOfEntitlement.scala.html
app/views/cob/ChangeAccountView.scala.html
app/views/cob/ConfirmNewAccountDetailsView.scala.html
app/views/components/Heading.scala.html
app/views/components/HeadingH2.scala.html
app/views/components/HeadingH3.scala.html
app/views/ftnae/ExtendPaymentsView.scala.html
app/views/paymenthistory/NoPaymentHistory.scala.html
app/views/paymenthistory/PaymentHistory.scala.html
test/views/cob/ChangeAccountViewSpec.scala
test/views/cob/ConfirmNewAccountDetailsViewSpec.scala

[[SB-1602]](https://jira.tools.tax.service.gov.uk/browse/SB-1602)
Move caption into headers for SR support and update all usages

[SB-1602] Captions contained in headers.

---

conf/messages.en

Missed during the last update.

[SB-1667] Missed punctuation update to a change.hidden message

---

app/views/ftnae/CannotFindYoungPersonView.scala.html
conf/messages.cy
conf/messages.en
test/utils/helpers/FtnaeControllerHelperSpec.scala

SB-1754 updates to cannot find young person page

---

app/controllers/ftnae/CheckYourAnswersController.scala
app/controllers/ftnae/WhichYoungPersonController.scala
app/models/UserAnswers.scala
app/views/ftnae/CheckYourAnswersView.scala.html
conf/messages.cy
conf/messages.en
test/controllers/ftnae/CheckYourAnswersControllerSpec.scala
test/controllers/ftnae/WhichYoungPersonControllerSpec.scala

Child not changed during check your answers:
QYP changed during check your answers:

SB-1752 Update Page - FTNAE check your answers

---

conf/messages.en

[[SB-1976]](https://jira.tools.tax.service.gov.uk/browse/SB-1976)
Requested update to English content for the Confirm Course Duration Page.

SB-1976: Update to Confirm Course Duration english content

---

conf/messages.cy

[[SB-1981]](https://jira.tools.tax.service.gov.uk/browse/SB-1981)
Updates to Welsh Course Duration page content subsequently following on change to English

[SB-1981]: Course Duration page Welsh updates

---

app/controllers/actions/FeatureFlagActionFactory.scala
app/views/ftnae/FtnaeDisabledView.scala.html
app/views/ftnae/FtnaeSwitchedOffView.scala.html
conf/messages.cy
conf/messages.en

I originally used the wording "SwitchedOff" but then replaced it with "Disabled" to better match the "Enabled" wording already used in FeatureFlagActionFactory. Having said that, if "SwitchedOff" or an alternative wording would be preferable, I'm happy to go forward with that wording instead.

SO-297 | New content for FTNAE when disabled

---

README.md

Updating the service's ReadMe prior to expected Live Service handover to list more details.

Update service read me
