hmrc/child-benefit-view-frontend

app/controllers/auth/ChildBenefitAuth.scala

Unfortunatelly service manager is running in Prod mode and and I don't think we can configure it via command line parameters to run in Dev mode. This will generate always absolute URL.

Add quick fix for service manager.

---

app/views/ProofOfEntitlement.scala.html

[SB-1127](https://jira.tools.tax.service.gov.uk/browse/SB-1127)
- Remove empty actions from Summary List that results in empty (and this indiscernible) links
[SB-1023](https://jira.tools.tax.service.gov.uk/browse/SB-1023)
- Add _govuk-link_ bootstrap class to Print this Page link to active expected focus highlighting

SB-1127/SB-1023: Accessibility Updates

---

app/utils/handlers/ErrorHandler.scala
test/controllers/ProofOfEntitlementControllerSpec.scala

[SB-1169](https://jira.tools.tax.service.gov.uk/browse/SB-1169)
Pushing error content out to user in the case of an internal service error is undesired for the platform going live as these typically contain technical or possible sensitive details.
Rather we will now ensure they are logged and redirect to the Service Down page to avoid anything internal being displayed

SB-1169: Do not show front end errors to users

---

app/services/PaymentHistoryService.scala

[SB-1210](https://jira.tools.tax.service.gov.uk/browse/SB-1210)
Formatted entitlement not being used for adjustment payment history page: corrected

SB-1210: formatted entitlement for adjustment payment history

---

app/controllers/CheckYourAnswersController.scala
app/controllers/NationalityQuestionController.scala
app/controllers/actions/FeatureFlagComposedActions.scala
app/controllers/cob/AccountChangedController.scala
app/controllers/cob/AccountNotChangedController.scala
app/controllers/cob/BARSLockOutController.scala
app/controllers/cob/CannotVerifyAccountController.scala
app/controllers/cob/ChangeAccountController.scala
app/controllers/cob/ConfirmNewAccountDetailsController.scala
app/controllers/cob/HICBCOptedOutPaymentsController.scala
app/controllers/cob/NewAccountDetailsController.scala
test-utils/testconfig/TestConfig.scala
test/controllers/CheckYourAnswersControllerSpec.scala
test/controllers/cob/AccountChangedControllerSpec.scala
test/controllers/cob/AccountNotChangedControllerSpec.scala
test/controllers/cob/BARSLockOutControllerSpec.scala
test/controllers/cob/CannotVerifyAccountControllerSpec.scala
test/controllers/cob/ChangeAccountControllerSpec.scala
test/controllers/cob/ConfirmNewAccountDetailsControllerSpec.scala
test/controllers/cob/HICBCOptedOutPaymentsControllerSpec.scala
test/controllers/cob/NewAccountDetailsControllerSpec.scala

[SB-1263](https://jira.tools.tax.service.gov.uk/browse/SB-1236)
My initial proposal for composed feature flag actions, reducing boiler plate code in controllers. This takes the common routes of action composition for feature flag actions (i.e. start with an ActionBuilder, filter based on the required feature flag and then run the IdentifierAction) and bundled them up into single calls to reduce boiler plate in Controllers.
These can then be further composed against with transformers (typically by getting and/or required session data) which are not universal to all controllers.
Developing this has raised questions over some of the test suites (such as feature flag config not being set in Unit Tests so these can fail of config is changed locally/there are no tests to ensure feature flag …

SB-1263: Initial composed feature action proposal

---

app/assets/stylesheets/application.scss
app/views/templates/Layout.scala.html
project/AppDependencies.scala

[SB-1327](https://jira.tools.tax.service.gov.uk/browse/SB-1327)
I spoke with the platform ui team and this is now standard way to suppress elements that require javascript functionality.
Functionally was introduced that add a "js-enabled" class the the body only if JS is itself enabled and this can be used to conditionally hide elements if it is not present.
JS Enabled:
JS Disabled:

Hide the back link element when JS is disabled

---

app/views/UnauthorisedView.scala.html
app/views/templates/Layout.scala.html
conf/messages.cy
conf/messages.en

[SB-1326](https://jira.tools.tax.service.gov.uk/browse/SB-1326)
Rearrange message files for comparability. Add immediately required Welsh messages.
- Change the HMRC Timeout Dialog to use the HMRC Timeout Dialog Helper: this collects some other data including the current language to correctly translate the "minutes" and "seconds" which is handled internally.
- Add missing Welsh translations that we require.
- Remove unused unauthorised.guidance paragraph from the unauthorised view.
- Rearrange the english and welsh message files to all contain the same section block titles in the same order. This will make our upcoming comparison of what is unavailable in welsh.

SB-1326: Welsh translations from Accessibility assessment

---

app/config/FeatureAllowlistFilter.scala
app/controllers/DummyFlagController.scala
app/controllers/PaymentHistoryController.scala
app/controllers/ProofOfEntitlementController.scala
app/controllers/actions/AllowlistAction.scala
app/controllers/actions/FeatureFlagActionFactory.scala
conf/application.conf
test-utils/testconfig/TestConfig.scala
test/controllers/DummyFlagControllerSpec.scala

This has been updated to have an allow list filter for each feature independently. This means each feature can define its own list of ips. For the features this has been applied to the `FeatureFlagActionFactory`
To keep the current behaviour for view proof of entitlement and payment history I have applied an independent `AllowlistAction`

SB-1286 - Ensure features have their own allowlist config

---

app/services/ChangeOfBankService.scala

[SB-1402](https://jira.tools.tax.service.gov.uk/browse/SB-1402)
Cleaning up use of magic number for a status in the change of bank code discovered whilst working on this issue

SB-1402: Remove NRS Code

---

app/utils/handlers/ErrorHandler.scala
test/utils/handlers/ErrorHandlerSpec.scala

Rely on inheritance of Request no that authcontext is not in use when…… auditing error handling
History:
The proof of entitlement path used to make use of the no defunct AuthContext, an object created with auth details on the current user. This had no inheritance relationship with Request[_] that is required for raising audits.
The cast to MessagesRequest[AnyContext] was specifically marshalled to over come this.
Now we make use of the IdentifierRequest which contains both the info that AuthContext used to and is still a super class of Request so this just meets the requirements.
Remove the asInstanceOf and this is what was throwing the exception and is no longer required.
Unit Tests for ErrorHandler and been atomised and expanded to check this still behaves.

Resolve unhandled exception in ErrorHandler fireAuditEvent

---

app/views/cob/ChangeAccountView.scala.html

[SB-1481](https://jira.tools.tax.service.gov.uk/browse/SB-1481)
A small error that does not affect the resulting HTML but is being picked up by our new accessibility testing job so resolving it.

Remove erroneous comma that is being flagged in accessibility tests

---

conf/messages.cy

[SB-1343](https://jira.tools.tax.service.gov.uk/browse/SB-1343)
Corrections to Welsh language file for WhyYoungPersonNotListed to match it's [Confluence page text](https://confluence.tools.tax.service.gov.uk/display/SCAChB/CHB3.14+Young+person+not+listed+for+FTNAE)

SB-1343: WYPNL Welsh Corrections

---

conf/messages.cy

[SB-1342](https://jira.tools.tax.service.gov.uk/browse/SB-1342)
Change to the Welsh on the Not Entitled (Course Employer Provided) page requested by the WLU.

Change to Welsh requested by the WLU

---

app/views/ftnae/PaymentsExtendedView.scala.html
conf/messages.cy
conf/messages.en

[SB-1339](https://jira.tools.tax.service.gov.uk/browse/SB-1339)
Welsh translations for the Payments Extended page as based it's [Confluence Page](https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=528745372)
Note: does not include the moved _change of cirsumstances_ call to action as this is part of [SB-1654](https://jira.tools.tax.service.gov.uk/browse/SB-1654)

Welsh Translation for the Payments Extended page

---

conf/messages.cy
conf/messages.en

[SB-1331](https://jira.tools.tax.service.gov.uk/browse/SB-1331)
Welsh translations for the Payments Extended page as based it's [Confluence Page](https://confluence.tools.tax.service.gov.uk/display/SCAChB/CHB3.02+Display+existing+ChB+data+for+QYP)

Finishing off the Welsh Translations for the Which Young Person Page

---

conf/messages.cy

[[SB-1338]](https://jira.tools.tax.service.gov.uk/browse/SB-1338)
Budd-dal Plant (Welsh for Child Benefit) is added to all page title's automatically (as well as GOV.UK), it is not required in the title text and is thus being currently being duplicated.

Remove generated title text from title message to remove duplication

---

app/views/ftnae/CannotFindYoungPersonView.scala.html

[[SB-1632]](https://jira.tools.tax.service.gov.uk/browse/SB-1632)
Accessibility issue spotted during testing of SB-1632, two links with non unique ids. Ids made unique to better support accessibility tools.

SB-1632: Unique ids for link on CannotFindYoungPerson view

---

app/controllers/cob/ConfirmNewAccountDetailsController.scala
app/services/ChangeOfBankService.scala
app/views/cob/AccountChangedView.scala.html
test-utils/generators/ModelGenerators.scala
test/controllers/cob/AccountChangedControllerSpec.scala
test/controllers/cob/ConfirmNewAccountDetailsControllerSpec.scala
test/services/ChangeOfBankServiceSpec.scala

[[SB-1655]](https://jira.tools.tax.service.gov.uk/browse/SB-1655)
Clear user's session on successful CoB submission and remove back link from the AccoundChangedView
Subsequent work will be raised to investigate adding functionality to the JourneyRecovery system should anyone fall outside of this.

SB-1655: Clear user's session after successful CoB submission

---

app/models/viewmodels/govuk/FieldsetFluency.scala
app/views/ftnae/WhichYoungPersonView.scala.html

[[SB-1661]](https://jira.tools.tax.service.gov.uk/browse/SB-1661)
Add new Legend Fluency to avoid non page heading legends being set to contain a h1.
This was something we have been missing as all previous legends have also been page headings.

[SB-1661] Structural fixes to the Which Young Person Page

---

conf/messages.en

[SB-1661](https://github.com/hmrc/child-benefit-view-frontend/pull/230/files) added a message for a legend - this got removed in main somehow. Possibly there was a conflict in the messages file during a merge? This PR adds it back in.

Add missing message

---

app/views/cob/ChangeAccountView.scala.html
app/views/components/ButtonLink.scala.html
app/views/ftnae/CheckYourAnswersView.scala.html

[[SB-1599]](https://jira.tools.tax.service.gov.uk/browse/SB-1599)
New component to centralise concerns of links as button and add the button role.
This is important for the likes of screen readers as certain controls interacts differently with anchor links and true buttons. Adding `role="button"` explicitly tells these tools to treat it as a button.
A similar link is on use in the FTNAE Check Your Answers view so this has been updated as well so it not later flagged when FT4 is audited.

[SB-1599] Links as Buttons give a role

---

conf/messages.cy

[[SB-1667]](https://jira.tools.tax.service.gov.uk/browse/SB-1667)
Resolution the Newid vs Newidiwch on visually hidden change text from WLU. They have confirmed all should start with the Newid provided by the Change link itself,

[SB-1667] Hidden change text updates from the WLU

---

app/controllers/ServiceUnavailableController.scala
test/controllers/ServiceUnavailableControllerSpec.scala

Example of HTTP GET for `/child-benefit/service-down`:

SB-1718 Change HTTP status code of Service Unavailable page to 503

---

app/views/components/Link.scala.html
conf/messages.cy
conf/messages.en
test/views/cob/HICBCOptedOutPaymentsViewSpec.scala

[SB-1622] which will implement the fix for [SB-1609]
Make '(opens in new tab)' text global and tied to link's behaviour. This reduces the need to adding 'open's in a new tab'/'yn agor tab newydd' to link text through the messages file and ensure that a link that is set to open in a new tab states so we cannot get divergence.

[SB-1622]: Behaviour driven '(opens in new tab)'

---

conf/messages.cy

CoB Change Successful Welsh message: full stop apart of link text rather than whole message.
Discovered whilst testing [[SB-1609]](https://jira.tools.tax.service.gov.uk/browse/SB-1609).

Incorrectly places full stop in messages

---

app/views/ftnae/WhyYoungPersonNotListedView.scala.html
conf/messages.cy
conf/messages.en

Screenshots of extra bullet point:

SB-1753 Add extra bullet point

---

app/views/NoAccountFoundView.scala.html
app/views/ProofOfEntitlement.scala.html
app/views/paymenthistory/NoPaymentHistory.scala.html
app/views/paymenthistory/PaymentHistory.scala.html

[[SB-1551]](https://jira.tools.tax.service.gov.uk/browse/SB-1551)
Remove back link from pages where there is no determinate previous step to go back to at the request of the design team.
Update Screen shots:-
No Account Found
Payment History (w/ payment history)
Payment History (w/o payment history)
View Proof of Entitlement

[SB-1551]: Remove inapplicable back links

---

app/forms/cob/WhatTypeOfAccountFormProvider.scala
app/models/WithMessage.scala
app/models/cob/WhatTypeOfAccount.scala
app/views/cob/NewAccountDetailsView.scala.html
app/views/cob/WhatTypeOfAccountView.scala.html
conf/messages.cy
conf/messages.en

[[SB-1849]](https://jira.tools.tax.service.gov.uk/browse/SB-1849)
Add a new account type to Change of Bank, Credit Union, with it's own set of messaging.

[SB-1849] Add the Credit Union account type to Change of Bank

---

app/controllers/actions/VerifyHICBCAction.scala
app/services/AuditService.scala
app/services/ChangeOfBankService.scala
app/utils/helpers/ClaimantBankInformationHelper.scala
app/views/ViewUtils.scala
app/views/cob/ChangeAccountView.scala.html
conf/messages.cy
conf/messages.en
test/controllers/cob/ChangeAccountControllerSpec.scala
test/services/AuditServiceSpec.scala
test/views/cob/ChangeAccountViewSpec.scala

Change display of existing Bank Details per accessibility recommendations.
The Sort Code is to be fully displayed and the Account Number is phrased as "ending in {last 4 digits}" to better be read using assistive technologies.

[SB-1606]: Update display of existing bank details

---

app/views/cob/NewAccountDetailsView.scala.html
conf/messages.cy

CoB: Do not display warning about account in another name for credit union accounts
Also incorporates [SB-2032](https://jira.tools.tax.service.gov.uk/browse/SB-2032) the temp values would cause issues for testing and releasing so since the Welsh has since been provided, getting it on to prevent issues.

[SB-1849]: Do not display account name warning credit union accounts

---

app/views/components/ConfirmationPanel.scala.html
app/views/ftnae/PaymentsExtendedView.scala.html
conf/messages.cy
conf/messages.en

[[SO-164]](https://jira.tools.tax.service.gov.uk/browse/SO-164)
We display the name of the child in the Confirmation Panel and the title of the page to re-enforce whom the journey was for (previously in the copy below on the page but less obvious).

SO-164: Confirm Child's Name in FTNAE Success

---

app/models/viewmodels/ErrorMessageAwareness.scala
app/views/cob/ChangeAccountView.scala.html
app/views/components/AdditionalScript.scala.html
conf/messages.cy
conf/messages.en
test/views/cob/ChangeAccountViewSpec.scala

[[SO-50](https://jira.tools.tax.service.gov.uk/browse/SO-50)
Fixing a few WGAC issues identified with visually hidden text (typically used by assistive technologies) as identified by our Accessibility Audits.
* The ErrorMessage model we import has an optional parameter to set the visually hidden prefix message for individual error messages which details the the string "Error". This was never overridden but has no been done so with the message "site.error".
* The GovukWarningText component that we import was searching for a message with the key "site.warning", this has been added.
* The ChangeAccountView was using HTML to build out a warning block rather than a standard component and was using hard coded English text, moved to the component to bring it in line and also enable Welsh …

[SO-50] Corrections to visually hidden A11Y text across features

---

test/controllers/cob/WhatTypeOfAccountControllerSpec.scala

[[SO-274]](https://jira.tools.tax.service.gov.uk/browse/SO-274)
Removing some old TODO statements. Mock seems to work fine so if there ever referred to anything less straight-forward, this is no longer the case.

[SO-274] Remove old and redundant TODO statements

---

app/controllers/actions/DataRequiredAction.scala
app/controllers/actions/FtnaePaymentsExtendedPageDataRequiredAction.scala
app/controllers/ftnae/CheckYourAnswersController.scala
app/utils/navigation/Navigator.scala
app/views/JourneyRecoveryContinueView.scala.html
app/views/JourneyRecoveryStartAgainView.scala.html
conf/messages.cy
conf/messages.en
test/controllers/actions/FtnaePaymentsExtendedPageDataRequiredActionSpec.scala
test/controllers/ftnae/CheckYourAnswersControllerSpec.scala
test/controllers/ftnae/HowManyYearsControllerSpec.scala
test/controllers/ftnae/LiveWithYouInUKControllerSpec.scala
test/controllers/ftnae/SchoolOrCollegeControllerSpec.scala
test/controllers/ftnae/TwelveHoursAWeekControllerSpec.scala
test/controllers/ftnae/WillCourseBeEmployerProvidedControllerSpec.scala
test/controllers/ftnae/WillYoungPersonBeStayingControllerSpec.scala
test/messages/MessagesSpec.scala

[[SO-297]|https://jira.tools.tax.service.gov.uk/browse/SO-279]
Update message files for parity and a new Unit Test that will check for this.
Also, made some corrections to the use of the JourneyRecovery route that came out of discovering that this was still running the the default place holder text and hadn't been fully configured.

SO-279: Complete parity between messages files (and corrections to Journey Recovery discovered)
